# Generated by Django 4.0.2 on 2022-07-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Admin', '0002_abuse_reports_bug_reports_to_do_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abuse_reports',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.AddField(
            model_name='bug_reports',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.AddField(
            model_name='log_record',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.AlterField(
            model_name='abuse_reports',
            name='violation',
            field=models.CharField(choices=[('Spam', 'Spam'), ('Copyright Violation', 'Copyright Violation'), ('Flagged Content', 'Flagged Content')], default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('System Admin', 'System Admin'), ('Management Team', 'Management Team'), ('Site Admin', 'Site Admin')], default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='bug_reports',
            name='category',
            field=models.CharField(choices=[('Data Loss', 'Data Loss'), ('Profile Registration', 'Profile Registration'), ('Messaging', 'Messaging')], default=0, max_length=300),
        ),
    ]
