# Generated by Django 4.0.2 on 2022-07-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_abuse_reports_user_bug_reports_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='password', max_length=32),
        ),
    ]
