# Generated by Django 4.0.4 on 2022-06-10 10:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('genre', models.CharField(max_length=16)),
                ('format', models.CharField(max_length=16)),
                ('link', models.URLField()),
                ('distributor', models.CharField(max_length=16)),
                ('distributor_id', models.UUIDField()),
                ('producer', models.IntegerField()),
                ('content_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('distributor', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=32)),
                ('cell_no', models.SmallIntegerField()),
                ('distributor_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('reference', models.URLField()),
                ('user', models.CharField(max_length=16)),
                ('like_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=32)),
                ('cell_no', models.SmallIntegerField()),
                ('_class', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('producer', models.IntegerField()),
                ('distributor', models.IntegerField()),
                ('upload_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Partners.content')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='producer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Partners.distributor'),
        ),
    ]
