# Generated by Django 4.0.2 on 2022-07-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
    ]
