# Generated by Django 4.0.2 on 2022-07-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
